name: bicep-deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy from'
        required: false
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || 'main' }}
          
      - name: 🔍 Verify deployment files
        run: |
          echo "=== Checking Bicep files to deploy ==="
          echo "Current commit: $(git rev-parse HEAD)"
          echo "servicebus.bicep (first 30 lines):"
          head -30 infra/bicep/modules/servicebus.bicep
          echo "\n=== main.bicep (last 20 lines) ==="
          tail -20 infra/bicep/main.bicep

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure Bicep CLI
        run: az bicep install

      - name: Deploy Bicep
        run: |
          az group create -n rg-ehms-prod -l eastus
          az deployment group create \
            --resource-group rg-ehms-prod \
            --template-file infra/bicep/main.bicep \
            --parameters prefix=ehmsprod pgAdminPassword=${{ secrets.PG_ADMIN_PASSWORD }}